apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-postgres-yaml
spec:
  project: default
  source: 
    repoURL: https://github.com/damianlaur7/argoLaur.git
    targetRevision: main
    path: postgres
  destination:
    server: https://kubernetes.default.svc
    namespace: argoLaur
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
      